name: Update Contributions

on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: "0 */12 * * 0,2,4,6"
  

jobs:
  contributions-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          template: "assets/templates/README.md.tpl"
          writeTo: "README.md"

      - uses: actions/upload-artifact@v4
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update Generated Readme
          branch: master
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>

      
      
